/* eslint-disable preserve-caught-error */
import { confirmPasswordReset, verifyPasswordResetCode } from 'firebase/auth'
import { auth, isFirebaseConfigured } from '../config/firebase'
const generic = 'Invalid email, user ID, or password.'
const resolveEmail = (identifier) => { const value = identifier.trim(); if (/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)) return value; if (value.toLowerCase() === (import.meta.env.VITE_ADMIN_LOGIN_ID || '').trim().toLowerCase()) return import.meta.env.VITE_ADMIN_EMAIL || null; return null }
const ready = () => { if (!isFirebaseConfigured) throw new Error('Firebase configuration is required.') }
export async function login(identifier, password, remember) { ready(); const email = resolveEmail(identifier); if (!email) throw new Error(generic); const { browserLocalPersistence, browserSessionPersistence, setPersistence, signInWithEmailAndPassword } = await import('firebase/auth'); try { await setPersistence(auth, remember ? browserLocalPersistence : browserSessionPersistence); return await signInWithEmailAndPassword(auth, email, password) } catch { throw new Error(generic) } }
export async function requestPasswordReset(identifier) { ready(); const email = resolveEmail(identifier); if (!email) throw new Error('Enter the configured admin email or User ID.'); try { const { sendPasswordResetEmail } = await import('firebase/auth'); await sendPasswordResetEmail(auth, email, { url: `${window.location.origin}/reset-password`, handleCodeInApp: true }); } catch (error) { if (error.code === 'auth/unauthorized-continue-uri') throw new Error('This site URL is not authorized in Firebase Authentication. Add this domain to Authorized domains.'); if (error.code === 'auth/user-not-found') throw new Error('No reset-enabled account matches that email.'); throw new Error('Reset email could not be sent. Check Firebase Email/Password and the authorized domain.') } }
export async function checkResetCode(code) { ready(); if (!code) throw new Error('The reset link is missing its code.'); return verifyPasswordResetCode(auth, code) }
export async function finishPasswordReset(code, password) { ready(); if (!password || password.length < 8) throw new Error('Use a password with at least 8 characters.'); await confirmPasswordReset(auth, code, password) }
export async function changePassword(currentPassword, newPassword) { ready(); const { EmailAuthProvider, reauthenticateWithCredential, updatePassword } = await import('firebase/auth'); try { const credential = EmailAuthProvider.credential(auth.currentUser.email, currentPassword); await reauthenticateWithCredential(auth.currentUser, credential); await updatePassword(auth.currentUser, newPassword) } catch (error) { throw new Error(error.code === 'auth/requires-recent-login' ? 'Please sign in again before changing your password.' : 'We could not change your password. Check your current password and try again.') } }
export const logout = async () => { if (isFirebaseConfigured) { const { signOut } = await import('firebase/auth'); return signOut(auth) } }