import { get, ref, update } from 'firebase/database'
import { rtdb } from '../config/firebase'
const COLLECTIONS=['masterOptions','clients','projects','accounts','accountTransfers','income','expenses','recurringExpenseTemplates','projectDocuments','credentials','credentialVaultConfigs','notificationPreferences','notificationStates','recordVersions','settings']
const text=new TextEncoder();const decode=new TextDecoder();const bytes=(x)=>btoa(String.fromCharCode(...new Uint8Array(x)));const fromBytes=(x)=>Uint8Array.from(atob(x),c=>c.charCodeAt(0));
async function keyFor(passphrase,salt){const material=await crypto.subtle.importKey('raw',text.encode(passphrase),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:310000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
const recordsFrom=(tree)=>Object.fromEntries(COLLECTIONS.map(name=>[name,Object.entries(tree?.[name]||{}).map(([id,data])=>({id,data}))]))
export async function createEncryptedBackup(uid,{includeVersions=false,passphrase}){if(!passphrase||passphrase.length<12)throw new Error('Use a backup passphrase of at least 12 characters.');const snapshot=await get(ref(rtdb,`users/${uid}`));const records=recordsFrom(snapshot.val()||{});if(!includeVersions)delete records.recordVersions;const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await keyFor(passphrase,salt);const payload=text.encode(JSON.stringify({format:'fm-encrypted-backup',version:2,storage:'rtdb',exportedAt:new Date().toISOString(),records}));const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,payload);return JSON.stringify({format:'fm-encrypted-backup',version:2,kdf:'PBKDF2-SHA-256',iterations:310000,salt:bytes(salt),iv:bytes(iv),ciphertext:bytes(ciphertext)})}
export async function readEncryptedBackup(fileText,passphrase){const file=JSON.parse(fileText);if(file.format!=='fm-encrypted-backup'||![1,2].includes(file.version))throw new Error('This is not a valid encrypted Freelance Manager backup.');const key=await keyFor(passphrase,fromBytes(file.salt));try{return JSON.parse(decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:fromBytes(file.iv)},key,fromBytes(file.ciphertext))))}catch{throw new Error('Backup could not be decrypted. Check the passphrase.')}}
export async function restoreSafeBackup(uid,backup){if(!backup?.records||typeof backup.records!=='object')throw new Error('Backup structure is invalid.');const allowed=['settings','masterOptions','clients','projects','projectDocuments','credentials','credentialVaultConfigs','notificationPreferences','notificationStates'];const patch={};let restored=0;for(const name of allowed)for(const item of backup.records[name]||[]){if(!item?.id||!item.data||typeof item.data!=='object')continue;if((item.data.ownerId&&item.data.ownerId!==uid)||(item.data.ownerUid&&item.data.ownerUid!==uid))continue;patch[`${name}/${item.id}`]={...item.data,ownerId:item.data.ownerId||uid,ownerUid:item.data.ownerUid||uid,updatedAt:Date.now(),updatedBy:uid};restored++}if(Object.keys(patch).length)await update(ref(rtdb,`users/${uid}`),patch);return restored}
export const FINANCIAL_BACKUP_COLLECTIONS=['accounts','accountTransfers','income','expenses','recurringExpenseTemplates']
