let xlsxLoader; let pdfLoader; const loadXlsx = () => xlsxLoader ||= import('xlsx'); const loadPdf = () => pdfLoader ||= import('jspdf');
import { collection, getDocs, query, where } from 'firebase/firestore'
import { db } from '../config/firebase'
import { csvText } from '../utils/csv'
import { toMinorUnits, formatCurrency } from '../utils/money'
import { createClient } from './clients'
import { createProject } from './projects'
import { createAccount, createIncome } from './financial'
import { createExpense } from './expenses'

export const DATA_TYPES = ['Clients', 'Projects', 'Income', 'Expenses', 'Accounts']
const schemas = {
  Clients: ['Name', 'Email', 'Phone', 'Client Type', 'Status'],
  Projects: ['Name', 'Client ID', 'Project Type', 'Status', 'Currency', 'Total Amount', 'Start Date'],
  Income: ['Title', 'Amount', 'Account ID', 'Currency', 'Received Date', 'Income Category', 'Payment Mode', 'Source Type', 'Project ID', 'Client ID', 'Payment Type'],
  Expenses: ['Title', 'Amount', 'Currency', 'Expense Type', 'Category', 'Expense Date', 'Payment Status', 'Account ID', 'Payment Mode', 'Paid Date', 'Project ID', 'Client ID'],
  Accounts: ['Name', 'Account Type', 'Currency', 'Opening Balance', 'Status'],
}
const key = (value) => String(value || '').trim()
const date = (value) => /^\d{4}-\d{2}-\d{2}$/.test(key(value)) && !Number.isNaN(new Date(`${value}T12:00:00`).getTime())
export const safeExportFilename = (type, format) => `${key(type).replace(/[^a-z0-9]+/gi, '_')}_Export_${new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19)}.${format}`
export const templateRows = (type) => [schemas[type] || []]
export async function parseRows(file, text) { const XLSX = await loadXlsx(); if (/\.xlsx$/i.test(file.name)) { const book = XLSX.read(text, { type: 'array' }); return XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]], { defval: '' }) } const [headers, ...lines] = new TextDecoder().decode(text).replace(/^\uFEFF/, '').split(/\r?\n/).filter(Boolean); if (!headers) throw new Error('The file is empty.'); const parsed = XLSX.utils.sheet_to_json(XLSX.read(new TextEncoder().encode([headers, ...lines].join('\n')), { type: 'array' }).Sheets.Sheet1, { defval: '' }); return parsed }
export function validateImport(type, rows, existing = {}) { const required = schemas[type] || []; const errors = []; const valid = []; const names = new Set((existing[type] || []).map((item) => key(item.name).toLowerCase())); rows.forEach((raw, index) => { const row = Object.fromEntries(Object.entries(raw).map(([field, value]) => [field.trim(), key(value)])); const issues = []; required.forEach((field) => { if (['Email', 'Phone', 'Project ID', 'Client ID', 'Payment Type', 'Paid Date'].includes(field)) return; if (!row[field]) issues.push(`${field} is required`); }); if (row.Amount && (!/^\d+(\.\d{1,2})?$/.test(row.Amount) || toMinorUnits(row.Amount) <= 0)) issues.push('Amount must be a positive monetary value'); ['Start Date', 'Received Date', 'Expense Date', 'Paid Date'].forEach((field) => { if (row[field] && !date(row[field])) issues.push(`${field} must use YYYY-MM-DD`); }); if (type === 'Clients' && row.Name && names.has(row.Name.toLowerCase())) issues.push('Duplicate client name'); if (type === 'Projects' && row['Client ID'] && !existing.clientIds?.has(row['Client ID'])) issues.push('Client ID does not exist'); if (['Income', 'Expenses'].includes(type) && row['Account ID'] && !existing.accountIds?.has(row['Account ID'])) issues.push('Account ID does not exist'); if (['Income', 'Expenses'].includes(type) && row['Project ID'] && !existing.projectIds?.has(row['Project ID'])) issues.push('Project ID does not exist'); if (issues.length) errors.push({ row: index + 2, reasons: issues }); else { valid.push(row); if (type === 'Clients') names.add(row.Name.toLowerCase()) } }); return { valid, errors, total: rows.length } }
const recordRows = (type, records, lookups, settings) => records.map((item) => { const amount = item.amountMinor === undefined ? '' : formatCurrency(item.amountMinor, item.currency || settings.currency, settings.locale); if (type === 'Clients') return { ID: item.id, Name: item.name, Email: item.email || '', Phone: item.phone || '', Status: item.status || '', 'Client Type': item.clientTypeId || '' }; if (type === 'Projects') return { ID: item.id, Name: item.name, 'Client ID': item.clientId, Client: lookups.clients[item.clientId]?.name || '', Status: item.status, Currency: item.currency || '', 'Total Amount': amount, 'Start Date': item.startDate?.toDate?.().toISOString().slice(0, 10) || '' }; if (type === 'Accounts') return { ID: item.id, Name: item.name, Currency: item.currency, Status: item.status, 'Opening Balance': formatCurrency(item.openingBalanceMinor || 0, item.currency, settings.locale), 'Current Balance': formatCurrency(item.currentBalanceMinor || 0, item.currency, settings.locale) }; return { ID: item.id, Title: item.title, Amount: amount, Currency: item.currency, Status: item.status || item.paymentStatus, 'Project ID': item.projectId || '', Project: lookups.projects[item.projectId]?.name || '', 'Client ID': item.clientId || '', Date: (item.receivedDate || item.expenseDate)?.toDate?.().toISOString().slice(0, 10) || '' } })
export async function loadExportData(uid, type, settings) { const collectionName = { Clients: 'clients', Projects: 'projects', Income: 'income', Expenses: 'expenses', Accounts: 'accounts' }[type]; const [records, clients, projects] = await Promise.all([getDocs(query(collection(db, collectionName), where('ownerId', '==', uid))), getDocs(query(collection(db, 'clients'), where('ownerId', '==', uid))), getDocs(query(collection(db, 'projects'), where('ownerId', '==', uid)))]); return recordRows(type, records.docs.map((doc) => ({ id: doc.id, ...doc.data() })), { clients: Object.fromEntries(clients.docs.map((doc) => [doc.id, doc.data()])), projects: Object.fromEntries(projects.docs.map((doc) => [doc.id, doc.data()])) }, settings) }
export async function downloadExport(type, format, rows) { const XLSX = format === 'csv' ? null : await loadXlsx(); const filename = safeExportFilename(type, format); if (format === 'csv') { const headers = Object.keys(rows[0] || { 'No records': '' }); const blob = new Blob([csvText(headers, rows.map((row) => headers.map((header) => row[header])))] , { type: 'text/csv;charset=utf-8' }); return download(blob, filename) } if (format === 'xlsx') { const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, XLSX.utils.json_to_sheet(rows), type); return download(new Blob([XLSX.write(book, { type: 'array', bookType: 'xlsx' })], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }), filename) } const { jsPDF } = await loadPdf(); const pdf = new jsPDF(); pdf.text(`${type} Export`, 14, 16); let y = 26; rows.slice(0, 40).forEach((row) => { pdf.text(Object.values(row).join(' | ').slice(0, 170), 14, y); y += 7; if (y > 280) { pdf.addPage(); y = 16 } }); pdf.save(filename) }
function download(blob, name) { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url) }
export async function importValidated(uid, type, rows) { for (const row of rows) { if (type === 'Clients') await createClient(uid, { name: row.Name, normalizedName: row.Name.toLowerCase(), email: row.Email || null, phone: row.Phone || null, clientTypeId: row['Client Type'] || 'Other', status: row.Status || 'Active' }); if (type === 'Projects') await createProject(uid, { name: row.Name, normalizedName: row.Name.toLowerCase(), clientId: row['Client ID'], projectTypeId: row['Project Type'], status: row.Status || 'Planning', priority: 'Medium', currency: row.Currency || 'INR', totalAmountMinor: toMinorUnits(row['Total Amount']), receivedAmountMinor: 0, startDate: new Date(`${row['Start Date']}T12:00:00`) }); if (type === 'Accounts') await createAccount(uid, { name: row.Name, accountTypeId: row['Account Type'], currency: row.Currency || 'INR', openingBalanceMinor: toMinorUnits(row['Opening Balance']), status: row.Status || 'Active' }); if (type === 'Income') await createIncome(uid, { title: row.Title, amountMinor: toMinorUnits(row.Amount), accountId: row['Account ID'], currency: row.Currency, receivedDate: row['Received Date'], incomeCategoryId: row['Income Category'], paymentModeId: row['Payment Mode'], sourceType: row['Source Type'], projectId: row['Project ID'] || null, clientId: row['Client ID'] || null, paymentTypeId: row['Payment Type'] || null }); if (type === 'Expenses') await createExpense(uid, { title: row.Title, amountMinor: toMinorUnits(row.Amount), currency: row.Currency, expenseType: row['Expense Type'], categoryId: row.Category, expenseDate: row['Expense Date'], paymentStatus: row['Payment Status'], accountId: row['Account ID'] || null, paymentModeId: row['Payment Mode'] || null, paidDate: row['Paid Date'] || null, projectId: row['Project ID'] || null, clientId: row['Client ID'] || null }) } }