import { subscribeRtdbCollection, subscribeRtdbFiltered, getRtdbRecord, createRtdbRecord, updateRtdbRecord, transactUserRoot, newRtdbId } from './rtdbRecords'
import { EXPENSE_PAYMENT_STATUSES, EXPENSE_TYPES, expenseAccountDeltas, nextRecurringDate, recurrenceKey } from '../utils/expenseLogic'
const ACTIVE='Active'; const clean=(v)=>String(v||'').trim(); const date=(v)=>clean(v).slice(0,10)||null; const amount=(v)=>{if(!Number.isSafeInteger(v)||v<=0)throw new Error('Enter an expense amount greater than zero.')};
const audit=(uid,old,next)=>({...next,ownerId:old?.ownerId||uid,ownerUid:old?.ownerUid||uid,createdAt:old?.createdAt||Date.now(),updatedAt:Date.now(),createdBy:old?.createdBy||uid,updatedBy:uid})
const sort=(field)=>(items)=>items.slice().sort((a,b)=>String(b[field]||'').localeCompare(String(a[field]||'')))
export const subscribeExpenses=(uid,cb,error)=>subscribeRtdbCollection(uid,'expenses',(x)=>cb(sort('expenseDate')(x)),error)
export const subscribeProjectExpenses=(uid,id,cb,error)=>subscribeRtdbFiltered(uid,'expenses',x=>x.projectId===id,(x)=>cb(sort('expenseDate')(x)),error)
export const subscribeClientExpenses=(uid,id,cb,error)=>subscribeRtdbFiltered(uid,'expenses',x=>x.clientId===id,(x)=>cb(sort('expenseDate')(x)),error)
export const subscribeMonthlyPaidExpenses=(uid,start,end,cb,error)=>subscribeRtdbFiltered(uid,'expenses',x=>x.paymentStatus==='Paid'&&x.paidDate>=date(start)&&x.paidDate<=date(end),(x)=>cb(sort('paidDate')(x)),error)
export const subscribeMonthlyPendingExpenses=(uid,end,cb,error)=>subscribeRtdbFiltered(uid,'expenses',x=>x.paymentStatus==='Pending'&&x.dueDate<=date(end),(x)=>cb(sort('dueDate')(x)),error)
export const subscribeRecurringTemplates=(uid,cb,error)=>subscribeRtdbCollection(uid,'recurringExpenseTemplates',(x)=>cb(x.slice().sort((a,b)=>String(a.nextOccurrenceDate).localeCompare(String(b.nextOccurrenceDate)))),error,'nextOccurrenceDate')
const cleanExpense=(v)=>({title:clean(v.title),amountMinor:v.amountMinor,currency:clean(v.currency),expenseType:v.expenseType,categoryId:v.categoryId,subcategoryId:v.subcategoryId||null,description:clean(v.description)||null,expenseDate:date(v.expenseDate),dueDate:date(v.dueDate),paidDate:v.paymentStatus==='Paid'?date(v.paidDate):null,accountId:v.paymentStatus==='Paid'?v.accountId:null,paymentModeId:v.paymentStatus==='Paid'?v.paymentModeId:null,paymentStatus:v.paymentStatus,clientId:v.clientId||null,projectId:v.projectId||null,vendorId:v.vendorId||null,transactionReference:clean(v.transactionReference)||null,notes:clean(v.notes)||null,isClientReimbursable:Boolean(v.isClientReimbursable),reimbursementNotes:clean(v.reimbursementNotes)||null,reimbursementWaived:Boolean(v.reimbursementWaived),reimbursementWaivedReason:v.reimbursementWaived?clean(v.reimbursementWaivedReason)||null:null,documentIds:Array.isArray(v.documentIds)?v.documentIds:[],recurringTemplateId:v.recurringTemplateId||null,recurrenceOccurrenceDate:date(v.recurrenceOccurrenceDate),isArchived:Boolean(v.isArchived)})
const validate=(v)=>{amount(v.amountMinor);if(!clean(v.title)||!clean(v.currency)||!EXPENSE_TYPES.includes(v.expenseType)||!clean(v.categoryId)||!date(v.expenseDate)||!EXPENSE_PAYMENT_STATUSES.includes(v.paymentStatus))throw new Error('Complete the required expense fields.');if(v.paymentStatus==='Paid'&&(!clean(v.accountId)||!clean(v.paymentModeId)||!date(v.paidDate)))throw new Error('Paid expenses require an account, payment mode and paid date.')}
const apply=(state,deltas,currency,stamp,activeIds=[])=>Object.entries(deltas).forEach(([id,delta])=>{if(!delta)return;const account=state.accounts?.[id];if(!account)throw new Error('A linked account is unavailable.');if(account.currency!==currency)throw new Error('Expense and account currencies must match.');if(activeIds.includes(id)&&account.status!==ACTIVE)throw new Error('Choose an active account for a paid expense.');state.accounts[id]={...account,currentBalanceMinor:(account.currentBalanceMinor||0)+delta,lastTransactionDate:stamp||account.lastTransactionDate,updatedAt:Date.now()}})
export async function createExpense(uid,v,fixedId=null){validate(v);const next=cleanExpense(v),id=fixedId||newRtdbId(uid,'expenses');await transactUserRoot(uid,(state)=>{state.expenses ||= {};if(state.expenses[id])return;const deltas=expenseAccountDeltas(null,next);apply(state,deltas,next.currency,next.paidDate,next.paymentStatus==='Paid'?[next.accountId]:[]);state.expenses[id]=audit(uid,null,{...next,ledgerReference:`expense:${id}`,cancelledAt:null,cancelledBy:null,cancellationReason:null,isDeleted:false});return state});return {id}}
export async function updateExpense(uid,id,v,{confirmBalanceChange=false}={}){validate(v);const next=cleanExpense(v);await transactUserRoot(uid,(state)=>{const old=state.expenses?.[id];if(!old||old.paymentStatus==='Cancelled')throw new Error('This expense cannot be edited. Restore it first.');const deltas=expenseAccountDeltas(old,next);if(Object.keys(deltas).length&&!confirmBalanceChange&&(old.paymentStatus==='Paid'||next.paymentStatus==='Paid'))throw new Error('Confirm the account balance change before saving.');apply(state,deltas,next.currency,next.paidDate||old.paidDate,next.paymentStatus==='Paid'?[next.accountId]:[]);state.expenses[id]=audit(uid,old,{...next,ledgerReference:`expense:${id}`});return state})}
export async function cancelExpense(uid,id,reason){if(!clean(reason))throw new Error('A cancellation reason is required.');await transactUserRoot(uid,(state)=>{const old=state.expenses?.[id];if(!old||old.paymentStatus==='Cancelled')throw new Error('Expense cannot be cancelled.');const next={...old,paymentStatus:'Cancelled',paymentStatusBeforeCancellation:old.paymentStatus,cancelledAt:Date.now(),cancelledBy:uid,cancellationReason:clean(reason)};apply(state,expenseAccountDeltas(old,next),old.currency,old.paidDate);state.expenses[id]=audit(uid,old,next);return state})}
export async function restoreExpense(uid,id){await transactUserRoot(uid,(state)=>{const old=state.expenses?.[id];if(!old||old.paymentStatus!=='Cancelled')throw new Error('Expense cannot be restored.');const status=old.paymentStatusBeforeCancellation||'Pending',next={...old,paymentStatus:status,cancelledAt:null,cancelledBy:null,cancellationReason:null};apply(state,expenseAccountDeltas(old,next),old.currency,old.paidDate,status==='Paid'?[old.accountId]:[]);state.expenses[id]=audit(uid,old,next);return state})}
export const getExpense=(uid,id)=>getRtdbRecord(uid,'expenses',id)
export const createRecurringTemplate=(uid,v)=>createRtdbRecord(uid,'recurringExpenseTemplates','Recurring expense template',{...v,title:clean(v.title),startDate:date(v.startDate),endDate:date(v.endDate),nextOccurrenceDate:date(v.nextOccurrenceDate),isActive:v.isActive!==false,isDeleted:false,lastGeneratedAt:null})
export const updateRecurringTemplate=(uid,id,v)=>updateRtdbRecord(uid,'recurringExpenseTemplates','Recurring expense template',id,{...v,startDate:v.startDate===undefined?undefined:date(v.startDate),endDate:v.endDate===undefined?undefined:date(v.endDate),nextOccurrenceDate:v.nextOccurrenceDate===undefined?undefined:date(v.nextOccurrenceDate)})
export async function generateDueExpenses(uid,templates,today=new Date().toISOString().slice(0,10)){let made=0;for(const template of templates.filter(x=>x.isActive&&x.nextOccurrenceDate)){let occurrence=date(template.nextOccurrenceDate),end=date(template.endDate);while(occurrence<=today&&(!end||occurrence<=end)){const id=recurrenceKey(template.id,occurrence);const before=await getRtdbRecord(uid,'expenses',id);if(!before){await createExpense(uid,{title:template.title,amountMinor:template.amountMinor,currency:template.currency,expenseType:template.expenseType,categoryId:template.categoryId,subcategoryId:template.subcategoryId,clientId:template.clientId,projectId:template.projectId,vendorId:template.vendorId,expenseDate:occurrence,dueDate:occurrence,paymentStatus:template.defaultPaymentStatus||'Pending',paidDate:template.defaultPaymentStatus==='Paid'?occurrence:null,accountId:template.defaultAccountId||null,paymentModeId:template.defaultPaymentModeId||null,notes:template.notes,recurringTemplateId:template.id,recurrenceOccurrenceDate:occurrence,isClientReimbursable:false},id);made++}occurrence=nextRecurringDate(occurrence,template.frequency,template.customIntervalDays)}await updateRecurringTemplate(uid,template.id,{nextOccurrenceDate:occurrence,lastGeneratedAt:Date.now()})}return made}

