import { subscribeRtdbCollection, subscribeRtdbFiltered, getRtdbRecord, createRtdbRecord, updateRtdbRecord, transactUserRoot, newRtdbId } from './rtdbRecords'
import { incomeAccountDeltas, projectPaymentSummary, transferDeltas } from '../utils/financialConsistency'
const ACTIVE='Active'; const VOIDED='Voided'; const clean=(v)=>String(v||'').trim(); const date=(v)=>clean(v).slice(0,10)||null; const minor=(v,label='Amount')=>{if(!Number.isSafeInteger(v)||v<=0)throw new Error(`${label} must be greater than zero.`)}
const order=(field)=>(items)=>items.slice().sort((a,b)=>String(b[field]||'').localeCompare(String(a[field]||'')))
export const subscribeAccounts=(uid,cb,error)=>subscribeRtdbCollection(uid,'accounts',cb,error)
export const subscribeIncome=(uid,cb,error)=>subscribeRtdbCollection(uid,'income',(x)=>cb(order('receivedDate')(x)),error)
export const subscribeTransfers=(uid,cb,error)=>subscribeRtdbCollection(uid,'accountTransfers',(x)=>cb(order('transferDate')(x)),error)
export const subscribeMonthlyIncome=(uid,start,end,cb,error)=>subscribeRtdbFiltered(uid,'income',(x)=>x.receivedDate>=date(start)&&x.receivedDate<=date(end),cb,error,'receivedDate')
export const subscribeProjectIncome=(uid,projectId,cb,error)=>subscribeRtdbFiltered(uid,'income',(x)=>x.projectId===projectId,cb,error,'receivedDate')
export const dateToTimestamp=(v)=>date(v)
const audit=(uid,old,next)=>({...next,ownerId:old?.ownerId||uid,ownerUid:old?.ownerUid||uid,createdAt:old?.createdAt||Date.now(),updatedAt:Date.now(),createdBy:old?.createdBy||uid,updatedBy:uid})
const verifyAccount=(state,id,currency,active=false)=>{const account=state.accounts?.[id];if(!account)throw new Error('The selected account is unavailable.');if(active&&account.status!==ACTIVE)throw new Error('Choose an active account for a new transaction.');if(currency&&account.currency!==currency)throw new Error('Account currency does not match the transaction currency.');return account}
const applyDeltas=(state,deltas,stamp)=>Object.entries(deltas).forEach(([id,delta])=>{if(!delta)return;const account=state.accounts?.[id];if(!account)throw new Error('A linked account is unavailable.');state.accounts[id]={...account,currentBalanceMinor:(account.currentBalanceMinor||0)+delta,lastTransactionDate:stamp||account.lastTransactionDate,updatedAt:Date.now()}})
const recomputeProject=(state,uid,projectId)=>{if(!projectId)return;const project=state.projects?.[projectId];if(!project)throw new Error('The linked project is unavailable.');const payments=Object.entries(state.income||{}).map(([id,x])=>({id,...x})).filter(x=>x.status===ACTIVE&&x.sourceType==='Project Payment'&&x.projectId===projectId);const summary=projectPaymentSummary(project.totalAmountMinor||0,payments);const latest=payments.sort((a,b)=>String(b.receivedDate).localeCompare(String(a.receivedDate)))[0];state.projects[projectId]=audit(uid,project,{...project,...summary,lastPaymentDate:latest?.receivedDate||null})}
const incomeClean=(v)=>{minor(v.amountMinor);if(!clean(v.accountId)||!clean(v.currency)||!date(v.receivedDate)||!clean(v.incomeCategoryId)||!clean(v.paymentModeId))throw new Error('Amount, account, currency, received date, category and payment mode are required.');if(!['Project Payment','Independent Income'].includes(v.sourceType))throw new Error('Choose a valid income type.');if(v.sourceType==='Project Payment'&&(!clean(v.projectId)||!clean(v.clientId)||!clean(v.paymentTypeId)))throw new Error('Project payments require a project, client and payment type.');return {...v,title:clean(v.title),receivedDate:date(v.receivedDate),paymentTypeId:v.paymentTypeId||null,projectId:v.sourceType==='Project Payment'?v.projectId:null,clientId:v.clientId||null,status:v.status||ACTIVE}}
export async function createAccount(uid,v){if(!clean(v.name)||!clean(v.accountTypeId)||!clean(v.currency)||!Number.isSafeInteger(v.openingBalanceMinor))throw new Error('Complete the required account fields.');return createRtdbRecord(uid,'accounts','Account',{...v,name:clean(v.name),normalizedName:clean(v.name).toLowerCase(),currentBalanceMinor:v.openingBalanceMinor,status:v.status||ACTIVE,isDeleted:false})}
export const getAccount=(uid,id)=>getRtdbRecord(uid,'accounts',id)
export const updateAccount=(uid,id,v)=>updateRtdbRecord(uid,'accounts','Account',id,v)
export const archiveAccount=(uid,id,reason='')=>updateAccount(uid,id,{status:'Archived',archiveReason:clean(reason),archivedAt:Date.now()})
export const reactivateAccount=(uid,id)=>updateAccount(uid,id,{status:ACTIVE,archiveReason:null,archivedAt:null})
export async function createIncome(uid,v){const next=incomeClean(v);const id=newRtdbId(uid,'income');await transactUserRoot(uid,(state)=>{state.income ||= {};state.accounts ||= {};state.projects ||= {};verifyAccount(state,next.accountId,next.currency,true);state.income[id]=audit(uid,null,{...next,ledgerReference:`income:${id}`,voidedAt:null,voidReason:null});applyDeltas(state,incomeAccountDeltas(null,next),next.receivedDate);recomputeProject(state,uid,next.projectId);return state});return {id}}
export async function updateIncome(uid,id,v){const next=incomeClean(v);await transactUserRoot(uid,(state)=>{const old=state.income?.[id];if(!old||old.status===VOIDED)throw new Error('This income record cannot be edited.');verifyAccount(state,next.accountId,next.currency,true);state.income[id]=audit(uid,old,{...next,ledgerReference:`income:${id}`});applyDeltas(state,incomeAccountDeltas(old,next),next.receivedDate||old.receivedDate);recomputeProject(state,uid,old.projectId);recomputeProject(state,uid,next.projectId);return state})}
export async function voidIncome(uid,id,reason){if(!clean(reason))throw new Error('A void reason is required.');await transactUserRoot(uid,(state)=>{const old=state.income?.[id];if(!old||old.status===VOIDED)throw new Error('Income cannot be voided.');const next={...old,status:VOIDED,voidedAt:Date.now(),voidedBy:uid,voidReason:clean(reason)};state.income[id]=audit(uid,old,next);applyDeltas(state,incomeAccountDeltas(old,next),old.receivedDate);recomputeProject(state,uid,old.projectId);return state})}
export async function restoreIncome(uid,id){await transactUserRoot(uid,(state)=>{const old=state.income?.[id];if(!old||old.status!==VOIDED)throw new Error('Income cannot be restored.');verifyAccount(state,old.accountId,old.currency,true);const next={...old,status:ACTIVE,voidedAt:null,voidedBy:null,voidReason:null};state.income[id]=audit(uid,old,next);applyDeltas(state,incomeAccountDeltas(old,next),old.receivedDate);recomputeProject(state,uid,old.projectId);return state})}
const transferClean=(v)=>{minor(v.amountMinor);if(!clean(v.fromAccountId)||!clean(v.toAccountId)||v.fromAccountId===v.toAccountId||!clean(v.currency)||!date(v.transferDate))throw new Error('Choose two different accounts, amount, currency and date.');return {...v,transferDate:date(v.transferDate),status:v.status||ACTIVE}}
export async function createTransfer(uid,v){const next=transferClean(v);const id=newRtdbId(uid,'accountTransfers');await transactUserRoot(uid,(state)=>{verifyAccount(state,next.fromAccountId,next.currency,true);verifyAccount(state,next.toAccountId,next.currency,true);state.accountTransfers ||= {};state.accountTransfers[id]=audit(uid,null,next);applyDeltas(state,transferDeltas(null,next),next.transferDate);return state});return {id}}
export async function updateTransfer(uid,id,v){const next=transferClean(v);await transactUserRoot(uid,(state)=>{const old=state.accountTransfers?.[id];if(!old||old.status===VOIDED)throw new Error('Transfer cannot be edited.');verifyAccount(state,next.fromAccountId,next.currency,true);verifyAccount(state,next.toAccountId,next.currency,true);state.accountTransfers[id]=audit(uid,old,next);applyDeltas(state,transferDeltas(old,next),next.transferDate);return state})}
export async function voidTransfer(uid,id,reason){if(!clean(reason))throw new Error('A void reason is required.');await transactUserRoot(uid,(state)=>{const old=state.accountTransfers?.[id];if(!old||old.status===VOIDED)throw new Error('Transfer cannot be voided.');const next={...old,status:VOIDED,voidReason:clean(reason),voidedAt:Date.now()};state.accountTransfers[id]=audit(uid,old,next);applyDeltas(state,transferDeltas(old,next),old.transferDate);return state})}
export async function restoreTransfer(uid,id){await transactUserRoot(uid,(state)=>{const old=state.accountTransfers?.[id];if(!old||old.status!==VOIDED)throw new Error('Transfer cannot be restored.');verifyAccount(state,old.fromAccountId,old.currency,true);verifyAccount(state,old.toAccountId,old.currency,true);const next={...old,status:ACTIVE,voidReason:null,voidedAt:null};state.accountTransfers[id]=audit(uid,old,next);applyDeltas(state,transferDeltas(old,next),old.transferDate);return state})}
export const reconcileProjectPayments=async(uid,projectId)=>transactUserRoot(uid,(state)=>{recomputeProject(state,uid,projectId);return state})
export const updateProjectPaymentReminder=(uid,projectId,values)=>updateRtdbRecord(uid,'projects','Project',projectId,values)
