import { useCallback, useEffect, useMemo, useState } from "react";
import { Bell, CheckCheck, RefreshCw } from "lucide-react";
import { Link } from "react-router-dom";
import { Card, EmptyState, SearchField, Skeleton } from "../components/ui";
import { PageHeader } from "../components/PageHeader";
import { useDashboardData } from "../hooks/useDashboardData";
import { getNotificationPreferences, loadNotificationStates, markAllNotificationsRead, updateNotificationState } from "../services/notifications";
import { deriveNotifications } from "../utils/notificationLogic";
import { useAuth } from "../context/useAuth";
const toDate=x=>x?.toDate?.()||new Date(x);
export function useNotifications(){const {user,isConfigured,preview}=useAuth();const data=useDashboardData();const [states,setStates]=useState([]),[preferences,setPreferences]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");const refresh=useCallback(async()=>{if(!user||!isConfigured||preview)return;try{const [s,p]=await Promise.all([loadNotificationStates(user.uid),getNotificationPreferences(user.uid)]);setStates(s);setPreferences(p);setError("");}catch{setError("Notifications could not be loaded.");}finally{setLoading(false);}},[user,isConfigured,preview]);useEffect(()=>{const timer=setTimeout(refresh,0);const focus=()=>refresh();window.addEventListener("focus",focus);return()=>{clearTimeout(timer);window.removeEventListener("focus",focus)}},[refresh]);const all=useMemo(()=>deriveNotifications({projects:data.projects.items,expenses:data.expenses.items,clients:data.clients.items},new Date(),preferences||{}).filter(n=>{const state=states.find(x=>x.notificationId===n.notificationId);return !state?.dismissedAt&&(!state?.snoozedUntil||toDate(state.snoozedUntil)<=new Date());}).map(n=>({...n,state:states.find(x=>x.notificationId===n.notificationId)})),[data.projects.items,data.expenses.items,data.clients.items,preferences,states]);return {all,states,loading:loading||data.loading,error,refresh,uid:user?.uid};}
function NotificationRow({n,uid,onChange}){const state=n.state||{};const update=(fields)=>updateNotificationState(uid,n.notificationId,fields).then(onChange);return <article className={`notification-row ${n.severity}`}><Link to={n.path}><strong>{n.title}</strong><p>{n.body}</p></Link><div className="notification-actions"><button onClick={()=>update({readAt:state.readAt?null:new Date()})}>{state.readAt?"Unread":"Read"}</button><button onClick={()=>update({snoozedUntil:new Date(Date.now()+86400000)})}>Tomorrow</button><button onClick={()=>update({snoozedUntil:new Date(Date.now()+3*86400000)})}>3 days</button><button onClick={()=>{if(n.severity!=="critical"||window.confirm("Dismiss this critical notification?"))update({dismissedAt:new Date()})}}>Dismiss</button></div></article>}
export function NotificationsPage(){const {all,loading,error,refresh,uid}=useNotifications();const [filter,setFilter]=useState("All"),[term,setTerm]=useState("");const filtered=all.filter(n=>(filter==="All"||filter===n.entityType||filter==="Unread"&&!n.state?.readAt||filter==="Critical"&&n.severity==="critical")&&`${n.title} ${n.body}`.toLowerCase().includes(term.toLowerCase()));return <div className="page-view"><PageHeader title="Notifications" description="In-app operational alerts are evaluated while this app is running." icon={Bell}/><Card><div className="card-line"><SearchField value={term} onChange={e=>setTerm(e.target.value)} aria-label="Search notifications"/><span><button className="button button-secondary" onClick={refresh}><RefreshCw size={15}/>Refresh</button><button className="button button-secondary" onClick={()=>markAllNotificationsRead(uid,filtered.map(x=>x.notificationId)).then(refresh)}><CheckCheck size={15}/>Mark all read</button></span></div><div className="tabs">{["All","Unread","Critical","Project","Expense"].map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x}</button>)}</div>{loading?<Skeleton className="summary-skeleton"/>:error?<p className="error-text">{error} <button onClick={refresh}>Retry</button></p>:filtered.length?filtered.map(n=><NotificationRow key={n.notificationId} n={n} uid={uid} onChange={refresh}/>):<EmptyState icon={Bell} title="You’re all caught up" description="Resolved conditions disappear automatically; snoozed items return when due."/>}</Card></div>}
