import { useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { Search } from "lucide-react";
import { Card, EmptyState, SearchField } from "../components/ui";
import { PageHeader } from "../components/PageHeader";
import { universalSearch } from "../services/search";
import { useAuth } from "../context/useAuth";
export function SearchPage(){const {user,isConfigured}=useAuth();const [params,setParams]=useSearchParams();const [term,setTerm]=useState(params.get("q")||""),[results,setResults]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState("");const type=params.get("type")||"All";useEffect(()=>{const q=term.trim();const timer=setTimeout(async()=>{setParams(q?{q,type:type==="All"?undefined:type}:{});if(q.length<2){setResults([]);return;}if(!user||!isConfigured)return;setLoading(true);try{setResults(await universalSearch(user.uid,q,type));setError("");}catch{setError("Some search results could not be loaded. Check the deployed indexes and try again.");}finally{setLoading(false)}},250);return()=>clearTimeout(timer)},[term,type,user,isConfigured,setParams]);return <div className="page-view"><PageHeader title="Search Results" description="Safe metadata only—credentials never include encrypted or decrypted secret values." icon={Search}/><Card><SearchField autoFocus value={term} onChange={e=>setTerm(e.target.value)} placeholder="Search clients, projects, records and safe metadata"/>
<div className="tabs">{[["All","All"],["clients","Clients"],["projects","Projects"],["accounts","Accounts"],["income","Income"],["expenses","Expenses"],["projectDocuments","Documents"],["credentials","Credentials"]].map(([v,l])=><button className={type===v?"active":""} key={v} onClick={()=>setParams({q:term,type:v})}>{l}</button>)}</div>{loading?<p>Searching…</p>:error?<p className="error-text">{error}</p>:term.trim().length<2?<p className="muted">Enter at least two characters to search.</p>:results.length?<div className="search-results">{results.map(item=><Link key={`${item.entityType}-${item.id}`} to={item.path} className="search-result"><span className="badge">{item.entityLabel}</span><strong>{item.name||item.title||item.serviceName||"Untitled record"}</strong><p>{item.searchTextNormalized?.slice(0,160)}</p></Link>)}</div>:<EmptyState icon={Search} title="No matching safe metadata" description="Try another name, reference or category."/>}</Card></div>}
