import { useState } from 'react'
import { useAuth } from '../context/useAuth'
import { useMasterOptions } from '../hooks/useMasterOptions'
import { createMasterOption } from '../services/masterOptions'
import { toast } from 'sonner'
import { isRealtimeDatabaseConfigured } from '../config/firebase'
export function CreatableSelect({ group, value, onChange, disabled, required, error, name }) { const { options } = useMasterOptions(group); const { user, isConfigured, preview } = useAuth(); const [term, setTerm] = useState(''); const [saving, setSaving] = useState(false); const filtered = options.filter((item) => item.label.toLowerCase().includes(term.toLowerCase())); const create = async () => { const label = term.trim(); if (!label || options.some((item) => item.normalizedLabel === label.toLowerCase()) || !user || !isConfigured || preview) return; setSaving(true); try { const record = await createMasterOption(user.uid, { group, label, normalizedLabel: label.toLowerCase(), description: '', isActive: true, isSystem: false, sortOrder: options.length }); onChange?.(record.id); setTerm('') } catch (saveError) { toast.error(saveError.message || 'Option could not be saved.') } finally { setSaving(false) } }
 return <div className="creatable-select"><select className="input" name={name} value={value || ''} required={required} disabled={disabled} onChange={(event) => onChange?.(event.target.value)}><option value="">Select an option</option>{options.map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select><input className="input" value={term} disabled={disabled || preview || !isConfigured || !isRealtimeDatabaseConfigured} onChange={(event) => setTerm(event.target.value)} placeholder="Search or add an option" />{term && !filtered.length && <button className="button button-secondary" type="button" disabled={saving || preview || !isConfigured || !isRealtimeDatabaseConfigured} onClick={create}>Add Ã¢â‚¬Å“{term.trim()}Ã¢â‚¬Â</button>}{error && <small className="form-error">{error}</small>}</div> }


