import { useMemo, useState } from 'react'
import { X } from 'lucide-react'
import { toast } from 'sonner'
import { Button, Drawer, FormField, Input } from './ui'
import { useAuth } from '../context/useAuth'
import { useSettings } from '../context/useSettings'
import { useAccounts } from '../hooks/useData'
import { CreatableSelect } from './CreatableSelect'
import { createIncome } from '../services/financial'
import { formatCurrency, toMinorUnits } from '../utils/money'

export function PaymentDrawer({ project, client, open, onClose }) {
 const { user, preview } = useAuth(); const { settings } = useSettings(); const { items: accounts } = useAccounts(); const [form, setForm] = useState({ amount:'', receivedDate:new Date().toISOString().slice(0,10), accountId:'', paymentModeId:'', paymentTypeId:'', notes:'' }); const [saving,setSaving]=useState(false)
 const activeAccounts=useMemo(()=>accounts.filter(a=>a.status==='Active' && a.currency===(project?.currency||settings.currency)),[accounts,project,settings.currency]); if(!project)return null
 const save=async(event)=>{event.preventDefault(); const amountMinor=toMinorUnits(form.amount); const accountId = form.accountId || activeAccounts[0]?.id; if(!amountMinor||!accountId||!form.paymentModeId||!form.paymentTypeId)return toast.error(activeAccounts.length ? 'Complete the payment amount, date, method and type.' : 'Create an active receiving account in Settings before recording a payment.'); setSaving(true); try { await createIncome(user.uid,{sourceType:'Project Payment',title:`${project.name} payment`,amountMinor,accountId,clientId:project.clientId,projectId:project.id,incomeCategoryId:'project-payment',paymentTypeId:form.paymentTypeId,paymentModeId:form.paymentModeId,receivedDate:form.receivedDate,notes:form.notes,currency:project.currency||settings.currency}); toast.success('Payment recorded. Project totals updated.'); setForm({...form,amount:'',notes:''}); onClose() } catch(error) { toast.error(error.message || 'Payment could not be recorded.') } finally { setSaving(false) } }
 return <Drawer open={open} onClose={onClose}><div className="payment-drawer"><div className="drawer-title"><div><p>Record payment</p><h2>{project.name}</h2><span>{client?.name || 'Client unavailable'}</span></div><button className="icon-button" onClick={onClose} aria-label="Close payment drawer"><X size={19}/></button></div><div className="drawer-metrics"><Metric label="Quotation" value={project.totalAmountMinor} /><Metric label="Received" value={project.receivedAmountMinor} tone="success"/><Metric label="Pending" value={project.remainingAmountMinor} tone={project.remainingAmountMinor > 0 ? 'danger' : 'neutral'}/></div><form className="settings-form payment-form" onSubmit={save}><FormField label="Amount" required><Input inputMode="decimal" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="0.00" autoFocus/></FormField><FormField label="Date" required><Input type="date" value={form.receivedDate} onChange={e=>setForm({...form,receivedDate:e.target.value})}/></FormField><FormField label="Method of Payment" required><CreatableSelect group="paymentModes" value={form.paymentModeId} onChange={paymentModeId=>setForm({...form,paymentModeId})} /></FormField><FormField label="Payment Type" required><CreatableSelect group="paymentTypes" value={form.paymentTypeId} onChange={paymentTypeId=>setForm({...form,paymentTypeId})} /></FormField><FormField label="Notes"><Input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Optional note"/></FormField><Button type="submit" loading={saving} disabled={preview}>Add payment</Button></form></div></Drawer>
 function Metric({label,value,tone='neutral'}) { return <div><span>{label}</span><strong className={tone}>{formatCurrency(value || 0,project.currency||settings.currency,settings.locale)}</strong></div> }
}