const encoder = new TextEncoder(), decoder = new TextDecoder();
const b64 = (bytes) => btoa(String.fromCharCode(...new Uint8Array(bytes)));
const fromB64 = (value) => Uint8Array.from(atob(value), (c) => c.charCodeAt(0));
const iterations = 310000;
const aad = (ownerUid, credentialId, version) => encoder.encode(`${ownerUid}:${credentialId}:${version}`);
async function derive(passphrase, salt, count = iterations) { return crypto.subtle.deriveKey({ name: "PBKDF2", salt, iterations: count, hash: "SHA-256" }, await crypto.subtle.importKey("raw", encoder.encode(passphrase), "PBKDF2", false, ["deriveKey"]), { name: "AES-GCM", length: 256 }, false, ["encrypt", "decrypt"]); }
export async function setupVault(passphrase) { const salt = crypto.getRandomValues(new Uint8Array(16)), iv = crypto.getRandomValues(new Uint8Array(12)), raw = crypto.getRandomValues(new Uint8Array(32)), wrapping = await derive(passphrase, salt); const wrappedKey = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, wrapping, raw); return { config: { algorithm: "AES-GCM", encryptionVersion: 1, kdf: "PBKDF2-SHA-256", iterations, salt: b64(salt), wrappingIv: b64(iv), wrappedVaultKey: b64(wrappedKey) }, vaultKey: await crypto.subtle.importKey("raw", raw, "AES-GCM", false, ["encrypt", "decrypt"]) }; }
export async function unlockVault(passphrase, config) { const wrapping = await derive(passphrase, fromB64(config.salt), config.iterations); const raw = await crypto.subtle.decrypt({ name: "AES-GCM", iv: fromB64(config.wrappingIv) }, wrapping, fromB64(config.wrappedVaultKey)); return crypto.subtle.importKey("raw", raw, "AES-GCM", false, ["encrypt", "decrypt"]); }
export async function encryptCredential(vaultKey, ownerUid, credentialId, payload, version = 1) { const iv = crypto.getRandomValues(new Uint8Array(12)); const ciphertext = await crypto.subtle.encrypt({ name: "AES-GCM", iv, additionalData: aad(ownerUid, credentialId, version) }, vaultKey, encoder.encode(JSON.stringify(payload))); return { algorithm: "AES-GCM", encryptionVersion: version, iv: b64(iv), ciphertext: b64(ciphertext) }; }
export async function decryptCredential(vaultKey, ownerUid, credentialId, envelope) { const raw = await crypto.subtle.decrypt({ name: "AES-GCM", iv: fromB64(envelope.iv), additionalData: aad(ownerUid, credentialId, envelope.encryptionVersion) }, vaultKey, fromB64(envelope.ciphertext)); return JSON.parse(decoder.decode(raw)); }
export async function changeVaultPassphrase(vaultKey, passphrase) { const raw = await crypto.subtle.exportKey("raw", vaultKey); const salt = crypto.getRandomValues(new Uint8Array(16)), iv = crypto.getRandomValues(new Uint8Array(12)), wrapping = await derive(passphrase, salt); return { algorithm: "AES-GCM", encryptionVersion: 1, kdf: "PBKDF2-SHA-256", iterations, salt: b64(salt), wrappingIv: b64(iv), wrappedVaultKey: b64(await crypto.subtle.encrypt({ name: "AES-GCM", iv }, wrapping, raw)) }; }
export function generatePassword({ length = 20, upper = true, lower = true, numbers = true, symbols = true, ambiguous = false } = {}) { const groups = [[upper, "ABCDEFGHJKLMNPQRSTUVWXYZ"], [lower, "abcdefghijkmnopqrstuvwxyz"], [numbers, ambiguous ? "0123456789" : "23456789"], [symbols, "!@#$%^&*()-_=+"]].filter(([on]) => on).map(([, chars]) => chars); if (!groups.length || length < groups.length) throw new Error("Choose a character group and sufficient length."); const pick = (chars) => { const limit = Math.floor(0x100000000 / chars.length) * chars.length; let value; do value = crypto.getRandomValues(new Uint32Array(1))[0]; while (value >= limit); return chars[value % chars.length]; }; const result = groups.map(pick); const all = groups.join(""); while (result.length < length) result.push(pick(all)); for (let i = result.length - 1; i > 0; i -= 1) { const limit = Math.floor(0x100000000 / (i + 1)) * (i + 1); let value; do value = crypto.getRandomValues(new Uint32Array(1))[0]; while (value >= limit); const j = value % (i + 1); [result[i], result[j]] = [result[j], result[i]]; } return result.join(""); }
export const resetConfirmationValid = (value) => value === "RESET CREDENTIAL VAULT";
