import { useCallback, useEffect, useMemo, useState } from 'react'
import { onValue, ref } from 'firebase/database'
import { rtdb } from '../config/firebase'
import { useAuth } from './useAuth'
import { saveGlobalSettings } from '../services/firestore'
import { DEFAULT_SETTINGS, SettingsContext } from './settingsStore'
const cacheKey='fm-safe-branding'
const cachedSettings=()=>{try{return{...DEFAULT_SETTINGS,...JSON.parse(localStorage.getItem(cacheKey)||'{}')}}catch{return DEFAULT_SETTINGS}}
const cacheBranding=(settings)=>localStorage.setItem(cacheKey,JSON.stringify({brandName:settings.brandName,shortName:settings.shortName,logoUrl:settings.logoUrl,darkLogoUrl:settings.darkLogoUrl,faviconUrl:settings.faviconUrl,accentColor:settings.accentColor}))
export function SettingsProvider({children}){const{user,isConfigured,preview}=useAuth();const[settings,setSettings]=useState(cachedSettings);const[loading,setLoading]=useState(false);const[error,setError]=useState('');useEffect(()=>{if(!user||!isConfigured||preview||!rtdb)return undefined;return onValue(ref(rtdb,`users/${user.uid}/settings/global`),(snap)=>{const next={...DEFAULT_SETTINGS,...(snap.val()||{})};setSettings(next);cacheBranding(next);setLoading(false)},()=>{setError('Settings could not be loaded.');setLoading(false)})},[user,isConfigured,preview]);useEffect(()=>{document.title=settings.brandName||DEFAULT_SETTINGS.brandName;document.documentElement.dataset.density=settings.density||'comfortable';document.documentElement.dataset.reducedMotion=settings.reducedMotion?'reduce':'system';if(settings.accentColor)document.documentElement.style.setProperty('--brand',settings.accentColor);else document.documentElement.style.removeProperty('--brand');const icon=document.querySelector('link[rel="icon"]');if(icon&&settings.faviconUrl)icon.href=settings.faviconUrl;cacheBranding(settings)},[settings]);const save=useCallback(async(values)=>{if(!user||!isConfigured||preview)throw new Error('Settings are read-only until Firebase is configured.');if(!Object.keys(values).length)return true;setError('');const optimistic={...settings,...values};setSettings(optimistic);cacheBranding(optimistic);try{await saveGlobalSettings(user.uid,values);return true}catch(reason){setSettings(settings);cacheBranding(settings);setError(reason.message||'Settings could not be saved.');throw reason}},[user,isConfigured,preview,settings]);return <SettingsContext.Provider value={useMemo(()=>({settings,loading,error,save,readOnly:!user||!isConfigured||preview}),[settings,loading,error,save,user,isConfigured,preview])}>{children}</SettingsContext.Provider>}
